ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER ora_user IDENTIFIED BY 1234
DEFAULT TABLESPACE MYTS
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO ora_user;

ALTER SESSION SET "_ORACLE_SCRIPT" = true;

create user ex_user identified by 1234
DEFAULT TABLESPACE MYTS
TEMPORARY TABLESPACE temp;

grant dba to ex_user;
